#!/bin/bash
result=$((5#$(echo $WATER | tr 'water' '01234') + 5#$(echo $STIR | tr 'stir.' '01234')))
reversed_result=$(echo "obase=8;$result" | bc | tr '01234567' 'behlnort' | rev)
echo "Reversed Result in base bestchol: $reversed_result"
